global:
  cloudProvider: {}
  tracing: {}
  metrics: {}
  environment: {}

enabled: true
environment: development
replicaCount: 1
initialDelaySeconds: 600
nodePort: 30030 #for minikube deployment only
nodeSelector: {}
tolerations: []
affinity: {}

cloudProvider:
  flavor: openshift
  dockerRegistryUrl: my-registry-url.io

image:
  repository: replica-server
  # Overrides the image tag whose default is the chart appVersion.
  tag: "v0.0.1"

resources:
  enabled: false
  value:
    limits:
      cpu: 100m
      memory: 128Mi
    requests:
      cpu: 100m
      memory: 128Mi

env:
  port: 8080
  targetPort: 8080
  protocol: TCP
  logLevel: info
  logPrettyPrintEnabled: false
  responseCompressionEnabled: true
  requestPayloadLimit: 1mb
  tracing:
    enabled: false
    url: http://localhost:55681/v1/trace
  metrics:
    enabled: false
    url: http://localhost:55681/v1/metrics

dbConfig:
  host: localhost
  username: postgres
  password: postgres
  database: replica-server
  sslAuth:
    enabled: false
    secretName: secret-name
    certFileName: postgresql.crt
    keyFileName: postgresql.key
    caFileName: root.crt

objectStorageConfig:
  host: s3Host
  port: 9000
  protocol: http
  projectId:
    enabled: true
    value: 373e47ef2a58d

route:
  enabled: true
  path: /
